### ISSUE TITLE
Not working PTR requests

### ISSUE THREAD

**Issue by black-cerberon** [bhanupratapys/dnswarden#4]
Hello. I'm using DNSCrypt-proxy with your server (_dnswarden-dc1_ and _dnswarden-dc2_) and PTR requests work not correctly. 
tcpdump screenshot: https://i.imgur.com/xphO3Ey.jpg

**Comment by bhanupratapys** [comment]
Hi there!

PTR requests work, tested them both with dig and nslookup. Are you by any chance trying to capture only UDP packets in your tcpdump screenshot?

**Comment by black-cerberon** [comment]
> PTR requests work, tested them both with dig and nslookup. 
That's right, but if request many IP instead on, will be fail. Try it with various software with mass resolving IPs like qBittorrent. May it some DDoS security?
> Are you by any chance trying to capture only UDP packets in your tcpdump screenshot?
Nope, other domain requests shows in tcpdump.

**Comment by bhanupratapys** [comment]
> > PTR requests work, tested them both with dig and nslookup.
> 
> That's right, but if request many IP instead on, will be fail. Try it with various software with mass resolving IPs like qBittorrent. May it some DDoS security?
> 
> > Are you by any chance trying to capture only UDP packets in your tcpdump screenshot?
> 
> Nope, other domain requests shows in tcpdump.

Yes, for dnscrypt and plaintext dns the server's are implemented with bit stricter ddos protection rules. Although I haven't faced any problems till now while using qbittorrent with 100+ active torrents. Ddos protection rules are bit relaxed while using dns-over-https/tls, because dns-over-https/tls are running with cluster of servers behind them and can take hit with tons of queries per second but still the client is limited to appropriate number of queries. If anyone tries to stress test the server's, the client is banned for predefined amount of time (server bans me too) when the dos protection rule is triggered.

Try using dns-over-https server's with dnscrypt-proxy and see if the problem still persists.

**Comment by black-cerberon** [comment]
Done. Thanks for answers.
